{
	categoria : "imagen",
stringBusqueda = [
{id: "1", nombre: "Radiografía de Tórax"},
{id: "2", nombre: "Radiografía osteoarticular "},
{id: "3", nombre: "Radiografía de Columna "},
{id: "4", nombre: "Radiografía de Columna Total"},
{id: "5", nombre: "Radiografía de Pelvis"},
{id: "6", nombre: "Radiografía de Articulaciones Sacroiliacas"},
{id: "7", nombre: "Radiografía de Cráneo"},
{id: "8", nombre: "Radiografía de Cara"},
{id: "9", nombre: "Radiografía de Cavum rinofaríngeo"},
{id: "10", nombre: "Radiografía Renal y Vesical simple"},
{id: "11", nombre: "Radiografía de Abdomen"},
{id: "12", nombre: "Otras proyecciones Rx especiales"},
{id: "13", nombre: "Pielografía de eliminación"},
{id: "14", nombre: "Tránsito esofágico"},
{id: "15", nombre: "Estudio de videodeglución"},
{id: "16", nombre: "Estudio de esófago"},
{id: "17", nombre: "Estudio de intestino delgado"},
{id: "18", nombre: "Tránsito intestinal con marcadores"},
{id: "19", nombre: "Enema Baritada de doble contraste"},
{id: "20", nombre: "Uretrocistografía"},
{id: "21", nombre: "Fistulografía"},
{id: "22", nombre: "Histerosalpingografia"},
{id: "23", nombre: "Cavernosografia"},
{id: "24", nombre: "Ecotomografía Abdominal"},
{id: "25", nombre: "Ecotomografía Pelviana "},
{id: "26", nombre: "Ecotomografía Tiroides"},
{id: "27", nombre: "Ecotomografía Testicular"},
{id: "28", nombre: "Ecotomografía Mamaria"},
{id: "29", nombre: "Ecotomografía Transrectal de Próstata"},
{id: "30", nombre: "Ecotomografía Transvaginal"},
{id: "31", nombre: "Ecotomografía Partes Blandas Musculoesquelética"},
{id: "32", nombre: "Doppler carotideo"},
{id: "33", nombre: "Doppler renal"},
{id: "34", nombre: "Doppler abdominal"},
{id: "35", nombre: "Doppler testicular"},
{id: "36", nombre: "Doppler vascular periférico arterial y venoso"},
{id: "37", nombre: "Doppler mapeo venoso de extremidades inferiores"},
{id: "38", nombre: "Mamografía"},
{id: "39", nombre: "Densitometría"},
{id: "40", nombre: "Tomografía Computada de Cerebro y Fosa Posterior"},
{id: "41", nombre: "Tomografía Computada de Oídos"},
{id: "42", nombre: "Tomografía Computada Maxilofacial "},
{id: "43", nombre: "Tomografía Computada de Cuello"},
{id: "44", nombre: "Tomografía Computada de Tórax"},
{id: "45", nombre: "Tomografía Computada de Abdomen"},
{id: "46", nombre: "Tomografía Computada de Pelvis"},
{id: "47", nombre: "Tomografía Computada Osteoarticular"},
{id: "48", nombre: "Tomografía Computada de Columna"},
{id: "49", nombre: "Pielotac"},
{id: "50", nombre: "Dentascan"},
{id: "51", nombre: "Score de Calcio Coronario"},
{id: "52", nombre: "Angiotomografía de Arterias Coronarias"},
{id: "53", nombre: "Angiotomografía de Arteria Pulmonar"},
{id: "54", nombre: "Angiotomografía de Aorta"},
{id: "55", nombre: "Angiotomografía de Vasos Abdominales"},
{id: "56", nombre: "Angiotomografía de Arterias Renales"},
{id: "57", nombre: "Angiotomografía de Cuello"},
{id: "58", nombre: "Angiotomografía de Extremidades"},
{id: "59", nombre: "Resonancia Magnética de Cerebro"},
{id: "60", nombre: "Resonancia Magnética de Columna Cervical"},
{id: "61", nombre: "Resonancia Magnética de Columna Dorsal"},
{id: "62", nombre: "Resonancia Magnética de Columna Lumbar"},
{id: "63", nombre: "Resonancia Magnética de Articulación Sacro-iliaca"},
{id: "64", nombre: "Resonancia Magnética de Pelvis"},
{id: "65", nombre: "Resonancia Magnética Osteoarticular y de Partes blandas"},
{id: "66", nombre: "Resonancia Magnética de Cuello"},
{id: "67", nombre: "Resonancia Magnética de Abdomen"},
{id: "68", nombre: "Resonancia Magnética de Vías Biliares o Colangioresonancia"},
{id: "69", nombre: "Resonancia Magnética de Mamas"},
{id: "70", nombre: "Angio resonancia de Vasos Intracerebrales"},
{id: "71", nombre: "Angio resonancia de Vasos del Cuello"},
{id: "72", nombre: "Angio resonancia Aórtica"},
{id: "73", nombre: "Angio resonancia de Arterias Renales"},
{id: "74", nombre: "Angio resonancia de Extremidades"},
{id: "75", nombre: "Angioresonancia Cardíaca"},
{id: "76", nombre: "Espectroscopía"},
{id: "77", nombre: "Resonancia Funcional"},
{id: "78", nombre: "Resonancia con cuantificación de flujo de LCR"},
{id: "79", nombre: "Tractografía"},
{id: "80", nombre: "Neurografias"}
]
}